server:
  undertow:
    threads:
      worker: 10
      io: 2

spring:
  jpa:
    properties:
      jakarta: # Scrip para geração de migration
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: src/main/resources/db/hibernate/db_create.sql
              drop-target: src/main/resources/db/hibernate/db_drop.sql
              update-target: src/main/resources/db/hibernate/db_update.sql

postgres:
  url: localhost:5432
  username: postgres
  password: postgres
  db: core_cdc
  schema_default: core_cdc

mongodb:
  url: localhost:27017
  username: mongo
  password: mongo
  db: cdc
  uri: mongodb://mongo:mongo@localhost:27017/cdc?authSource=admin